# Generated by Django 2.2.3 on 2019-08-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_quotation',
            name='title',
            field=models.CharField(blank=True, db_column='title', max_length=600, null=True, verbose_name='契約件名'),
        ),
    ]
