# Generated by Django 2.2.3 on 2019-08-26 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_mainte', '0011_auto_20190826_1443'),
        ('contract', '0002_auto_20190826_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_quotation',
            options={'verbose_name': '見積テーブル', 'verbose_name_plural': '見積テーブル'},
        ),
        migrations.CreateModel(
            name='t_quotation_item',
            fields=[
                ('technical_level', models.CharField(blank=True, db_column='technical_level', max_length=50, null=True, verbose_name='職種')),
                ('man_month', models.DecimalField(blank=True, db_column='man_month', decimal_places=3, max_digits=7, null=True, verbose_name='工数(人月)')),
                ('tax_type', models.CharField(blank=True, db_column='tax_type', max_length=1, null=True, verbose_name='税区分')),
                ('tax_rate', models.DecimalField(blank=True, db_column='tax_rate', decimal_places=3, max_digits=4, null=True, verbose_name='税率')),
                ('contract_exclude_tax', models.DecimalField(blank=True, db_column='contract_exclude_tax', decimal_places=3, max_digits=13, null=True, verbose_name='契約額(税抜)')),
                ('contract_tax_amount', models.DecimalField(blank=True, db_column='contract_tax_amount', decimal_places=3, max_digits=13, null=True, verbose_name='契約額(税額)')),
                ('contract_amount', models.DecimalField(blank=True, db_column='contract_amount', decimal_places=3, max_digits=13, null=True, verbose_name='契約額(合計)')),
                ('unit_prices_minus', models.DecimalField(blank=True, db_column='unit_prices_minus', decimal_places=3, max_digits=13, null=True, verbose_name='精算単価_不足時')),
                ('unit_prices_plus', models.DecimalField(blank=True, db_column='unit_prices_plus', decimal_places=3, max_digits=13, null=True, verbose_name='精算単価_超過時')),
                ('unit_prices_flat', models.DecimalField(blank=True, db_column='unit_prices_flat', decimal_places=3, max_digits=13, null=True, verbose_name='精算単価_均一')),
                ('notes', models.TextField(blank=True, db_column='notes', null=True, verbose_name='備考')),
                ('delete_flg', models.BooleanField(db_column='delete_flg', default=False, verbose_name='削除フラグ')),
                ('ent_date', models.DateTimeField(db_column='ent_date', editable=False, verbose_name='登録日時')),
                ('ent_id', models.CharField(db_column='ent_id', editable=False, max_length=6, verbose_name='登録者')),
                ('upd_date', models.DateTimeField(blank=True, db_column='upd_date', editable=False, null=True, verbose_name='更新日時')),
                ('upd_id', models.CharField(blank=True, db_column='upd_id', editable=False, max_length=6, null=True, verbose_name='更新者')),
                ('upd_cnt', models.IntegerField(db_column='upd_cnt', default=0, editable=False, verbose_name='更新回数')),
                ('t_quotation_item_id', models.AutoField(db_column='t_quotation_item_id', editable=False, primary_key=True, serialize=False, verbose_name='見積内訳ID')),
                ('t_quotation_id', models.ForeignKey(db_column='t_quotation_id', on_delete=django.db.models.deletion.PROTECT, to='contract.t_quotation', verbose_name='見積ID')),
                ('t_staff_id', models.ForeignKey(db_column='t_staff_id', on_delete=django.db.models.deletion.PROTECT, to='master_mainte.t_staff', verbose_name='社員ID')),
            ],
            options={
                'verbose_name': '見積内訳テーブル',
                'verbose_name_plural': '見積内訳テーブル',
            },
        ),
    ]
