# Generated by Django 2.2.3 on 2019-08-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20190826_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_quotation_item',
            name='unit_prices_flat',
        ),
        migrations.AlterField(
            model_name='t_quotation_item',
            name='tax_type',
            field=models.CharField(blank=True, choices=[('1', '税込'), ('2', '税別')], db_column='tax_type', max_length=1, null=True, verbose_name='税区分'),
        ),
        migrations.AlterField(
            model_name='t_quotation_item',
            name='technical_level',
            field=models.CharField(blank=True, db_column='technical_level', max_length=20, null=True, verbose_name='職種'),
        ),
    ]
