# Generated by Django 2.2.3 on 2019-08-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_auto_20190826_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_quotation_item',
            name='ent_date',
            field=models.DateTimeField(db_column='ent_date', verbose_name='登録日時'),
        ),
    ]
