# Generated by Django 2.2.3 on 2019-08-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_mainte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_staff',
            name='image_filename',
            field=models.FileField(blank=True, db_column='image_filename', upload_to='uploads/', verbose_name='顔写真パス'),
        ),
    ]
