# Generated by Django 2.2.3 on 2019-08-08 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_mainte', '0002_auto_20190808_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_company',
            name='upd_date',
            field=models.DateTimeField(db_column='upd_date', editable=False, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='t_company',
            name='upd_id',
            field=models.CharField(db_column='upd_id', editable=False, max_length=6, verbose_name='更新者'),
        ),
        migrations.CreateModel(
            name='t_mydept',
            fields=[
                ('t_mydept_id', models.AutoField(db_column='t_mydept_id', editable=False, primary_key=True, serialize=False, verbose_name='自社組織ID')),
                ('mydept_name', models.CharField(db_column='mydept_name', max_length=150, verbose_name='自社組織名称')),
                ('jc_group_id', models.CharField(blank=True, db_column='jc_group_id', max_length=5, null=True, verbose_name='ジョブカングループコード')),
                ('jc_parent_group_id', models.CharField(blank=True, db_column='jc_parent_group_id', max_length=5, null=True, verbose_name='ジョブカン親グループコード')),
                ('delete_flg', models.BooleanField(db_column='delete_flg', default=False, verbose_name='削除フラグ')),
                ('ent_date', models.DateTimeField(db_column='ent_date', editable=False, verbose_name='登録日時')),
                ('ent_id', models.CharField(db_column='ent_id', editable=False, max_length=6, verbose_name='登録者')),
                ('upd_date', models.DateTimeField(db_column='upd_date', editable=False, verbose_name='更新日時')),
                ('upd_id', models.CharField(db_column='upd_id', editable=False, max_length=6, verbose_name='更新者')),
                ('upd_cnt', models.IntegerField(db_column='upd_cnt', default=0, editable=False, verbose_name='更新回数')),
                ('leader_t_staff_id', models.ForeignKey(db_column='leader_t_staff_id', on_delete=django.db.models.deletion.PROTECT, to='master_mainte.t_staff', verbose_name='リーダ社員番号')),
            ],
            options={
                'verbose_name': '自社組織テーブル',
                'verbose_name_plural': '自社組織テーブル',
                'ordering': ['jc_group_id'],
            },
        ),
    ]
