# Generated by Django 2.2.3 on 2019-08-08 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_mainte', '0003_auto_20190808_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_mydept',
            name='jc_group_id',
            field=models.CharField(blank=True, db_column='jc_group_id', max_length=5, null=True, unique=True, verbose_name='ジョブカングループコード'),
        ),
        migrations.AlterField(
            model_name='t_mydept',
            name='leader_t_staff_id',
            field=models.ForeignKey(db_column='leader_t_staff_id', on_delete=django.db.models.deletion.PROTECT, to='master_mainte.t_staff', verbose_name='リーダ'),
        ),
        migrations.AlterField(
            model_name='t_staff',
            name='staff_no',
            field=models.CharField(blank=True, db_column='staff_no', max_length=6, null=True, unique=True, verbose_name='社員番号'),
        ),
        migrations.CreateModel(
            name='t_staff_dept',
            fields=[
                ('t_staff_dept_id', models.AutoField(db_column='t_staff_dept_id', editable=False, primary_key=True, serialize=False, verbose_name='社員組織ID')),
                ('trans_date', models.DateField(db_column='trans_date', verbose_name='異動日')),
                ('position_id', models.CharField(choices=[('10', '社長'), ('20', '副社長'), ('30', '営業'), ('40', '事務'), ('50', '部長'), ('60', '課長'), ('70', '係長'), ('80', '社員')], db_column='position_id', default='80', max_length=2, verbose_name='役職コード')),
                ('delete_flg', models.BooleanField(db_column='delete_flg', default=False, verbose_name='削除フラグ')),
                ('ent_date', models.DateTimeField(db_column='ent_date', editable=False, verbose_name='登録日時')),
                ('ent_id', models.CharField(db_column='ent_id', editable=False, max_length=6, verbose_name='登録者')),
                ('upd_date', models.DateTimeField(blank=True, db_column='upd_date', editable=False, null=True, verbose_name='更新日時')),
                ('upd_id', models.CharField(blank=True, db_column='upd_id', editable=False, max_length=6, null=True, verbose_name='更新者')),
                ('upd_cnt', models.IntegerField(db_column='upd_cnt', default=0, editable=False, verbose_name='更新回数')),
                ('t_mydept_id', models.ForeignKey(db_column='t_mydept_id', on_delete=django.db.models.deletion.PROTECT, to='master_mainte.t_mydept', verbose_name='組織')),
                ('t_staff_id', models.ForeignKey(db_column='t_staff_id', on_delete=django.db.models.deletion.PROTECT, to='master_mainte.t_staff', verbose_name='社員')),
            ],
            options={
                'verbose_name': '社員組織テーブル',
                'verbose_name_plural': '社員組織テーブル',
                'ordering': ['t_staff_id', '-trans_date'],
                'unique_together': {('t_staff_id', 'trans_date')},
            },
        ),
    ]
