# Generated by Django 2.2.3 on 2019-08-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_mainte', '0004_auto_20190808_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_staff_dept',
            name='delete_flg',
        ),
        migrations.AddField(
            model_name='t_staff_dept',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True, verbose_name='生存フラグ'),
        ),
    ]
