# Generated by Django 2.2.3 on 2019-08-09 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_mainte', '0007_t_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_dept',
            name='t_company_id',
            field=models.ForeignKey(db_column='t_company_id', limit_choices_to={'company_type': 'OT'}, on_delete=django.db.models.deletion.PROTECT, to='master_mainte.t_company', verbose_name='会社ID'),
        ),
        migrations.CreateModel(
            name='t_manager',
            fields=[
                ('t_manager_id', models.AutoField(db_column='t_manager_id', editable=False, primary_key=True, serialize=False, verbose_name='担当者ID')),
                ('position', models.CharField(blank=True, db_column='position', max_length=100, null=True, verbose_name='担当者役職名')),
                ('fname', models.CharField(db_column='fname', max_length=90, verbose_name='担当者姓')),
                ('lname', models.CharField(db_column='lname', max_length=90, verbose_name='担当者名')),
                ('fname_k', models.CharField(blank=True, db_column='fname_k', max_length=90, null=True, verbose_name='担当者姓カナ')),
                ('lname_k', models.CharField(blank=True, db_column='lname_k', max_length=90, null=True, verbose_name='担当者名カナ')),
                ('fname_e', models.CharField(blank=True, db_column='fname_e', max_length=90, null=True, verbose_name='担当者姓英字')),
                ('lname_e', models.CharField(blank=True, db_column='lname_e', max_length=90, null=True, verbose_name='担当者名英字')),
                ('tel', models.CharField(blank=True, db_column='tel', max_length=15, null=True, verbose_name='TEL')),
                ('fax', models.CharField(blank=True, db_column='fax', max_length=15, null=True, verbose_name='FAX')),
                ('is_client', models.IntegerField(db_column='is_client', default=False, max_length=1, verbose_name='派遣先担当者フラグ')),
                ('is_dispatch', models.IntegerField(db_column='is_dispatch', default=False, max_length=1, verbose_name='派遣元担当者フラグ')),
                ('delete_flg', models.BooleanField(db_column='delete_flg', default=False, verbose_name='削除フラグ')),
                ('ent_date', models.DateTimeField(db_column='ent_date', editable=False, verbose_name='登録日時')),
                ('ent_id', models.CharField(db_column='ent_id', editable=False, max_length=6, verbose_name='登録者')),
                ('upd_date', models.DateTimeField(blank=True, db_column='upd_date', editable=False, null=True, verbose_name='更新日時')),
                ('upd_id', models.CharField(blank=True, db_column='upd_id', editable=False, max_length=6, null=True, verbose_name='更新者')),
                ('upd_cnt', models.IntegerField(db_column='upd_cnt', default=0, editable=False, verbose_name='更新回数')),
                ('t_company_id', models.ForeignKey(db_column='t_company_id', on_delete=django.db.models.deletion.PROTECT, to='master_mainte.t_company', verbose_name='会社ID')),
                ('t_dept_id', models.ForeignKey(db_column='t_dept_id', on_delete=django.db.models.deletion.PROTECT, to='master_mainte.t_dept', verbose_name='組織ID')),
            ],
            options={
                'verbose_name': '担当者テーブル',
                'verbose_name_plural': '担当者テーブル',
                'ordering': ['t_company_id', 't_dept_id', 'fname', 'lname'],
            },
        ),
    ]
