# Generated by Django 2.2.3 on 2019-08-26 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_mainte', '0010_auto_20190809_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_company',
            options={'ordering': ['company_type', 'company_name_k'], 'verbose_name': '0100_会社テーブル', 'verbose_name_plural': '0100_会社テーブル'},
        ),
        migrations.AlterModelOptions(
            name='t_dept',
            options={'ordering': ['t_company_id', 'dept_name'], 'verbose_name': '0600_組織テーブル', 'verbose_name_plural': '0600_組織テーブル'},
        ),
        migrations.AlterModelOptions(
            name='t_manager',
            options={'ordering': ['t_company_id', 't_dept_id', 'fname', 'lname'], 'verbose_name': '0700_担当者テーブル', 'verbose_name_plural': '0700_担当者テーブル'},
        ),
        migrations.AlterModelOptions(
            name='t_mydept',
            options={'ordering': ['jc_group_id'], 'verbose_name': '0300_自社組織テーブル', 'verbose_name_plural': '0300_自社組織テーブル'},
        ),
        migrations.AlterModelOptions(
            name='t_staff',
            options={'ordering': ['staff_no'], 'verbose_name': '0200_社員テーブル', 'verbose_name_plural': '0200_社員テーブル'},
        ),
        migrations.AlterModelOptions(
            name='t_staff_dept',
            options={'ordering': ['t_staff_id', '-trans_date'], 'verbose_name': '0400_社員組織テーブル', 'verbose_name_plural': '0400_社員組織テーブル'},
        ),
        migrations.AlterModelOptions(
            name='t_staff_hire',
            options={'ordering': ['t_staff_id', '-change_date'], 'verbose_name': '0500_社員雇用契約テーブル', 'verbose_name_plural': '0500_社員雇用契約テーブル'},
        ),
        migrations.AlterModelOptions(
            name='t_workplace',
            options={'ordering': ['t_company_id', 'workplace_name'], 'verbose_name': '0800_就業場所テーブル', 'verbose_name_plural': '0800_就業場所テーブル'},
        ),
    ]
